# yamllint disable

version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    target-branch: development
    allow:
      - dependency-type: all
    open-pull-requests-limit: 10
    reviewers: [ ppodolsky ]
    labels: [ dependencies, automatic ]
    schedule:
      interval: weekly
      time: "10:00"
      timezone: Europe/Moscow
  - package-ecosystem: github-actions
    directory: /
    target-branch: development
    open-pull-requests-limit: 10
    reviewers: [ ppodolsky ]
    labels: [ dependencies, automatic ]
    schedule:
      interval: weekly
      time: "10:00"
      timezone: Europe/Moscow