[tool.poetry]
name = "trident"
version = "0.1.0"
description = ""
authors = ["Pasha <ppodolsky@me.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
aiobaseclient = "^0.4.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
