http:
  endpoint: 0.0.0.0:80
iroh:
  author: h3fjmgdtvchk7sl4zatfuamzzjo2ms75pg3d6xamv6pub7cj4osa
  tables: {}
  path: /tmp/trident/iroh
  bind_port: 11204
  rpc_port: 4919
  max_rpc_connections: 32
  max_rpc_streams: 1024
  sinks: {}
  storages:
    default:
      shards:
      - name: shard1
        path: /tmp/trident/data/shard1
        weight: 1
      - name: shard2
        path: /tmp/trident/data/shard1
        weight: 1
      is_import_missing_enabled: false
  gc_interval_secs: 86400
