http:
  endpoint: 0.0.0.0:80
iroh:
  tables: {}
  path: /trident/iroh
  bind_port: 11204
  rpc_port: 4919
  max_rpc_connections: 32
  max_rpc_streams: 1024
  sinks: {}
  fs_storages:
    default:
      replicas: 1
      fs_shards:
        - name: shard1
          path: /trident/data/shard1
          weight: 1
        - name: shard2
          path: /trident/data/shard1
          weight: 1
  gc_interval_secs: 86400
